FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleqa:cuda126-py310-cibase
RUN apt update && apt install -y jq
RUN python -m pip install --no-cache-dir xgrammar==0.1.19 torch==2.6.0 -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
COPY ../../requirements.txt ./requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
COPY ./unittest_requirement.txt ./unittest_requirement.txt
RUN python -m pip install --no-cache-dir -r unittest_requirement.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
COPY ./requirements_paddle_nv.txt ./requirements_paddle_nv.txt
RUN python -m pip install --no-cache-dir -r requirements_paddle_nv.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
