# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from enum import Enum


class LoggingEventName(Enum):
    """
    Represents various event points in the system.
    """

    PREPROCESSING_START = "PREPROCESSING_START"
    PREPROCESSING_END = "PREPROCESSING_END"
    REQUEST_SCHEDULE_START = "REQUEST_SCHEDULE_START"
    REQUEST_QUEUE_START = "REQUEST_QUEUE_START"
    REQUEST_QUEUE_END = "REQUEST_QUEUE_END"
    RESOURCE_ALLOCATE_START = "RESOURCE_ALLOCATE_START"
    PREPARE_PREFIX_CACHE_START = "PREPARE_PREFIX_CACHE_START"
    PREPARE_PREFIX_CACHE_END = "PREPARE_PREFIX_CACHE_END"
    RESOURCE_ALLOCATE_END = "RESOURCE_ALLOCATE_END"
    REQUEST_SCHEDULE_END = "REQUEST_SCHEDULE_END"
    INFERENCE_START = "INFERENCE_START"
    FIRST_TOKEN_GENERATED = "FIRST_TOKEN_GENERATED"
    DECODE_START = "DECODE_START"
    INFERENCE_END = "INFERENCE_END"
    WRITE_CACHE_TO_STORAGE_START = "WRITE_CACHE_TO_STORAGE_START"
    WRITE_CACHE_TO_STORAGE_END = "WRITE_CACHE_TO_STORAGE_END"
    POSTPROCESSING_START = "POSTPROCESSING_START"
    POSTPROCESSING_END = "POSTPROCESSING_END"
    PREEMPTED = "PREEMPTED"
    RESCHEDULED_INFERENCE_START = "RESCHEDULED_INFERENCE_START"
    # New events for optimization
    CACHE_HIT = "CACHE_HIT"  # Prefix cache hit
    CACHE_MISS = "CACHE_MISS"  # Prefix cache miss

    # For Prefill Instance
    ASK_DECODE_RESOURCE_START = "ASK_DECODE_RESOURCE_START"
    ASK_DECODE_RESOURCE_END = "ASK_DECODE_RESOURCE_END"
    CHECK_CACHE_TRANSFER_START = "CHECK_CACHE_TRANSFER_START"
    CHECK_CACHE_TRANSFER_END = "CHECK_CACHE_TRANSFER_END"
    PREFILL_INFERENCE_END = "PREFILL_INFERENCE_END"

    # For Decode Instance
    DECODE_PROCESS_PREALLOCATE_REQUEST_START = "DECODE_PROCESS_PREALLOCATE_REQUEST_START"
    DECODE_PROCESS_PREALLOCAT_REQUEST_END = "DECODE_PROCESS_PREALLOCAT_REQUEST_END"
    DECODE_PROCESS_PREFILLED_REQUEST_START = "DECODE_PROCESS_PREFILLED_REQUEST_START"
    DECODE_PROCESS_PREFILLED_REQUEST_END = "DECODE_PROCESS_PREFILLED_REQUEST_END"
    DECODE_INFERENCE_END = "DECODE_INFERENCE_END"


class StageName(Enum):
    """
    Represents the main stages in the request processing flow.
    """

    PREPROCESSING = "PREPROCESSING"
    SCHEDULE = "SCHEDULE"
    PREFILL = "PREFILL"
    DECODE = "DECODE"
    POSTPROCESSING = "POSTPROCESSING"


EVENT_TO_STAGE_MAP = {
    LoggingEventName.PREPROCESSING_START: StageName.PREPROCESSING,
    LoggingEventName.PREPROCESSING_END: StageName.PREPROCESSING,
    LoggingEventName.REQUEST_SCHEDULE_START: StageName.SCHEDULE,
    LoggingEventName.REQUEST_QUEUE_START: StageName.SCHEDULE,
    LoggingEventName.REQUEST_QUEUE_END: StageName.SCHEDULE,
    LoggingEventName.RESOURCE_ALLOCATE_START: StageName.SCHEDULE,
    LoggingEventName.PREPARE_PREFIX_CACHE_START: StageName.SCHEDULE,
    LoggingEventName.PREPARE_PREFIX_CACHE_END: StageName.SCHEDULE,
    LoggingEventName.RESOURCE_ALLOCATE_END: StageName.SCHEDULE,
    LoggingEventName.REQUEST_SCHEDULE_END: StageName.SCHEDULE,
    LoggingEventName.CACHE_HIT: StageName.SCHEDULE,
    LoggingEventName.CACHE_MISS: StageName.SCHEDULE,
    LoggingEventName.INFERENCE_START: StageName.PREFILL,
    LoggingEventName.FIRST_TOKEN_GENERATED: StageName.PREFILL,
    LoggingEventName.DECODE_START: StageName.DECODE,
    LoggingEventName.PREEMPTED: StageName.DECODE,
    LoggingEventName.RESCHEDULED_INFERENCE_START: StageName.DECODE,
    LoggingEventName.INFERENCE_END: StageName.DECODE,
    LoggingEventName.WRITE_CACHE_TO_STORAGE_START: StageName.POSTPROCESSING,
    LoggingEventName.WRITE_CACHE_TO_STORAGE_END: StageName.POSTPROCESSING,
    LoggingEventName.POSTPROCESSING_START: StageName.POSTPROCESSING,
    LoggingEventName.POSTPROCESSING_END: StageName.POSTPROCESSING,
    LoggingEventName.ASK_DECODE_RESOURCE_START: StageName.SCHEDULE,
    LoggingEventName.ASK_DECODE_RESOURCE_END: StageName.SCHEDULE,
    LoggingEventName.CHECK_CACHE_TRANSFER_START: StageName.POSTPROCESSING,
    LoggingEventName.CHECK_CACHE_TRANSFER_END: StageName.POSTPROCESSING,
    LoggingEventName.PREFILL_INFERENCE_END: StageName.PREFILL,
    LoggingEventName.DECODE_PROCESS_PREALLOCATE_REQUEST_START: StageName.DECODE,
    LoggingEventName.DECODE_PROCESS_PREALLOCAT_REQUEST_END: StageName.DECODE,
    LoggingEventName.DECODE_PROCESS_PREFILLED_REQUEST_START: StageName.DECODE,
    LoggingEventName.DECODE_PROCESS_PREFILLED_REQUEST_END: StageName.DECODE,
    LoggingEventName.DECODE_INFERENCE_END: StageName.DECODE,
}
