from enum import Enum


class LoggingEventName(Enum):
    """
    表示系统中的各种事件点。
    """

    PREPROCESSING_START = "PREPROCESSING_START"
    PREPROCESSING_END = "PREPROCESSING_END"
    REQUEST_SCHEDULE_START = "REQUEST_SCHEDULE_START"
    REQUEST_QUEUE_START = "REQUEST_QUEUE_START"
    REQUEST_QUEUE_END = "REQUEST_QUEUE_END"
    RESOURCE_ALLOCATE_START = "RESOURCE_ALLOCATE_START"
    RESOURCE_ALLOCATE_END = "RESOURCE_ALLOCATE_END"
    REQUEST_SCHEDULE_END = "REQUEST_SCHEDULE_END"
    INFERENCE_START = "INFERENCE_START"
    FIRST_TOKEN_GENERATED = "FIRST_TOKEN_GENERATED"
    DECODE_START = "DECODE_START"
    INFERENCE_END = "INFERENCE_END"
    POSTPROCESSING_START = "POSTPROCESSING_START"
    POSTPROCESSING_END = "POSTPROCESSING_END"


class StageName(Enum):
    """
    表示请求处理流程中的主要阶段。
    """

    PREPROCESSING = "PREPROCESSING"
    SCHEDULE = "SCHEDULE"
    PREFILL = "PREFILL"
    DECODE = "DECODE"
    POSTPROCESSING = "POSTPROCESSING"


EVENT_TO_STAGE_MAP = {
    LoggingEventName.PREPROCESSING_START: StageName.PREPROCESSING,
    LoggingEventName.PREPROCESSING_END: StageName.PREPROCESSING,
    LoggingEventName.REQUEST_SCHEDULE_START: StageName.SCHEDULE,
    LoggingEventName.REQUEST_QUEUE_START: StageName.SCHEDULE,
    LoggingEventName.REQUEST_QUEUE_END: StageName.SCHEDULE,
    LoggingEventName.RESOURCE_ALLOCATE_START: StageName.SCHEDULE,
    LoggingEventName.RESOURCE_ALLOCATE_END: StageName.SCHEDULE,
    LoggingEventName.REQUEST_SCHEDULE_END: StageName.SCHEDULE,
    LoggingEventName.INFERENCE_START: StageName.PREFILL,
    LoggingEventName.FIRST_TOKEN_GENERATED: StageName.PREFILL,
    LoggingEventName.DECODE_START: StageName.DECODE,
    LoggingEventName.INFERENCE_END: StageName.DECODE,
    LoggingEventName.POSTPROCESSING_START: StageName.POSTPROCESSING,
    LoggingEventName.POSTPROCESSING_END: StageName.POSTPROCESSING,
}
