# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.0.0'
git_version = '361acdbef7d8d03cf03f0a2408b51f1c60a03e21'
