# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.0.0'
git_version = 'd0ff2db36e5483e46fd8f7a1d0e34c11b071963a'
