# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'fastdeploy'
    static_configs:
    # list all your targets here
      - targets: ['127.0.0.1:30000']
