# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.3.0'
git_version = '9d87046d78bcfc10c07b1e7a2bccda3914452201'
