# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.3.0'
git_version = 'e388f48a0d6b97fc09dd7bd64c4aaa0f5687690c'
