# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.3.0'
git_version = 'b69f13b26846f2e13f6ad3c81f1d4ad3ad81fdbb'
