/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InferDemo */

#ifndef EXAMPLES_APPLICATION_JAVA_YOLOV8_CPP_INFER_DEMO_H_
#define EXAMPLES_APPLICATION_JAVA_YOLOV8_CPP_INFER_DEMO_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InferDemo
 * Method:    infer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_InferDemo_infer
  (JNIEnv *env, jobject thiz, jstring modelPath, jstring imagePath);

#ifdef __cplusplus
}
#endif
#endif  // EXAMPLES_APPLICATION_JAVA_YOLOV8_CPP_INFER_DEMO_H_
