name: "cls_postprocess"
backend: "python"
max_batch_size: 1
input [
  {
    name: "POST_INPUT_0"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

output [
  {
    name: "POST_OUTPUT"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

instance_group [
  {
      count: 1
      kind: KIND_CPU
  }
]
