if(NOT CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
  message(FATAL_ERROR "Huawei Ascend NPU is supported on Linux aarch64 platform for now.")
endif()

if(NOT ${ENABLE_LITE_BACKEND})
  set(ENABLE_LITE_BACKEND ON)
endif()

if (NOT BUILD_FASTDEPLOY_PYTHON)
  message(STATUS "Build FastDeploy Ascend C++ library.")
  if(NOT PADDLELITE_URL)
    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_1121.tgz")
  endif()
else ()
  message(STATUS "Build FastDeploy Ascend Python library.")
  if(NOT PADDLELITE_URL)
    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_python_1207.tgz")
  endif()
endif()	
