if(NOT ${ENABLE_LITE_BACKEND})
  set(ENABLE_LITE_BACKEND ON)
endif()

if(NOT CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
  if (NOT BUILD_FASTDEPLOY_PYTHON)
    message(STATUS "Build FastDeploy Ascend C++ library on X86 platform.")
    if(NOT PADDLELITE_URL)
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_x86_huawei_ascend_npu_0105.tgz")
    endif()
  else ()
    message(STATUS "Build FastDeploy Ascend Python library on X86 platform.")
    if(NOT PADDLELITE_URL)
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_x86_huawei_ascend_npu_python_0105.tgz") 
    endif()
  endif()	
endif()



if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
  if (NOT BUILD_FASTDEPLOY_PYTHON)
    message(STATUS "Build FastDeploy Ascend C++ library on aarch64 platform.")
    if(NOT PADDLELITE_URL)
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_1121.tgz")
    endif()
  else ()
    message(STATUS "Build FastDeploy Ascend Python library on aarch64 platform.")
    if(NOT PADDLELITE_URL)
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_python_1207.tgz")
    endif()
  endif()	
endif()