if(NOT ENABLE_LITE_BACKEND)
  message("Will force to set ENABLE_LITE_BACKEND when build with KunlunXin.")
  set(ENABLE_LITE_BACKEND ON)
endif()

option(WITH_LITE_XPU_LOG "" ON)

if(NOT PADDLELITE_URL)
  if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-aarch64-xpu-v213.tgz")
  else ()
    if (WITH_LITE_XPU_LOG)
      # set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-20221215.tgz")
      # set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-20230303.tgz")
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-20230410.tgz")
    else()
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-x64-xpu-without-log-20230303.tgz")
    endif()
  endif()
endif()
