if (NOT DEFINED TARGET_ABI)
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
    set(CMAKE_C_COMPILER "gcc")
    set(CMAKE_CXX_COMPILER "g++")
    set(TARGET_ABI amd64)
else()
    if(NOT ${ENABLE_LITE_BACKEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_LITE_BACKEND=ON")
        set(ENABLE_LITE_BACKEND ON)
    endif()
    if(${ENABLE_PADDLE_FRONTEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_PADDLE_FRONTEND=OFF")
        set(ENABLE_PADDLE_FRONTEND OFF)
    endif()
    if(${ENABLE_ORT_BACKEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_ORT_BACKEND=OFF")
        set(ENABLE_ORT_BACKEND OFF)
    endif()
    if(${ENABLE_PADDLE_BACKEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_PADDLE_BACKEND=OFF")
        set(ENABLE_PADDLE_BACKEND OFF)
    endif()
    if(${ENABLE_OPENVINO_BACKEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_OPENVINO_BACKEND=OFF")
        set(ENABLE_OPENVINO_BACKEND OFF)
    endif()
    if(${ENABLE_TRT_BACKEND})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_TRT_BACKEND=OFF")
        set(ENABLE_TRT_BACKEND OFF)
    endif()

    if(${WITH_GPU})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DWITH_GPU=OFF")
        set(WITH_GPU OFF)
    endif()

    if(${ENABLE_OPENCV_CUDA})
        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_OPENCV_CUDA=OFF") 
        set(ENABLE_OPENCV_CUDA OFF) 
    endif()

    if(${ENABLE_TEXT})
        set(ENABLE_TEXT OFF CACHE BOOL "Force ENABLE_TEXT OFF" FORCE)
        message(STATUS "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_TEXT=OFF")
    endif()
    if (DEFINED CMAKE_INSTALL_PREFIX)
        install(FILES ${PROJECT_SOURCE_DIR}/cmake/xpu.cmake DESTINATION ${CMAKE_INSTALL_PREFIX})
    endif()
endif()


