if (NOT DEFINED TARGET_ABI)
    message(WARNING "TARGET_ABI is DEFINED, will set to TARGET_ABI=amd64")
    set(TARGET_ABI amd64)
endif()

if(NOT ${ENABLE_LITE_BACKEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_LITE_BACKEND=ON")
    set(ENABLE_LITE_BACKEND ON)
endif()
if(${ENABLE_PADDLE_FRONTEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_PADDLE_FRONTEND=OFF")
    set(ENABLE_PADDLE_FRONTEND OFF)
endif()
if(${ENABLE_ORT_BACKEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_ORT_BACKEND=OFF")
    set(ENABLE_ORT_BACKEND OFF)
endif()
if(${ENABLE_PADDLE_BACKEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_PADDLE_BACKEND=OFF")
    set(ENABLE_PADDLE_BACKEND OFF)
endif()
if(${ENABLE_OPENVINO_BACKEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_OPENVINO_BACKEND=OFF")
    set(ENABLE_OPENVINO_BACKEND OFF)
endif()
if(${ENABLE_TRT_BACKEND})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_TRT_BACKEND=OFF")
    set(ENABLE_TRT_BACKEND OFF)
endif()

if(${WITH_GPU})
    message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DWITH_GPU=OFF")
    set(WITH_GPU OFF)
endif()


