from paddle.base import core
import paddle
import inspect


def step_paddle_npu(
    stop_flags,
    seq_lens_this_time,
    ori_seq_lens_encoder,
    seq_lens_encoder,
    seq_lens_decoder,
    block_tables,
    encoder_block_lens,
    is_block_step,
    step_block_list,
    step_lens,
    recover_block_list,
    recover_lens,
    need_block_list,
    need_block_len,
    used_list_len,
    free_list,
    free_list_len,
    input_ids,
    pre_ids,
    step_idx,
    next_tokens,
    first_tokens_ids,
    block_size,
    encoder_decoder_block_num,
):

    (
        stop_flags_out,
        seq_lens_this_time_out,
        seq_lens_encoder_out,
        seq_lens_decoder_out,
        block_tables_out,
        encoder_block_lens_out,
        is_block_step_out,
        step_block_list_out,
        step_lens_out,
        recover_block_list_out,
        recover_lens_out,
        need_block_list_out,
        need_block_len_out,
        used_list_len_out,
        free_list_out,
        free_list_len_out,
        input_ids_out,
        first_token_ids_out,
    ) = core.eager._run_custom_op(
        "step_paddle_op",
        stop_flags,
        seq_lens_this_time,
        ori_seq_lens_encoder.cpu(),
        seq_lens_encoder,
        seq_lens_decoder,
        block_tables,
        encoder_block_lens.cpu(),
        is_block_step,
        step_block_list.cpu(),
        step_lens.cpu(),
        recover_block_list.cpu(),
        recover_lens.cpu(),
        need_block_list.cpu(),
        need_block_len.cpu(),
        used_list_len.cpu(),
        free_list.cpu(),
        free_list_len.cpu(),
        input_ids,
        pre_ids,
        step_idx,
        next_tokens,
        first_tokens_ids.cpu(),
        block_size,
        encoder_decoder_block_num,
    )

    return (
        stop_flags_out,
        seq_lens_this_time_out,
        seq_lens_encoder_out,
        seq_lens_decoder_out,
        block_tables_out,
        encoder_block_lens_out,
        is_block_step_out,
        step_block_list_out,
        step_lens_out,
        recover_block_list_out,
        recover_lens_out,
        need_block_list_out,
        need_block_len_out,
        used_list_len_out,
        free_list_out,
        free_list_len_out,
        input_ids_out,
        first_token_ids_out,
    )
