name: FastDeploy Linux GPU Build Task
description: "FastDeploy packages build and upload"

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        description: "Build Images"
        required: true
        default: "ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleqa:cuda126-py310"
      COMPILE_ARCH:
        description: "Build GPU Archs"
        required: true
        default: "80,90"
      WITH_NIGHTLY_BUILD:
        description: "Enable nightly build mode (e.g. add date suffix to version)"
        required: false
        default: "ON"
      FD_VERSION:
        description: "FastDeploy Package Version"
        required: false
        default: ""
      UPLOAD:
        description: "Upload Package"
        required: true
        default: "ON"
jobs:
  fd-build:
    runs-on: [self-hosted, GPU-Build-Use]
  steps:
    - name: Code Prepare
      shell: bash
      env:
        docker_image: ${{ inputs.DOCKER_IMAGE }}
        IS_PR: ${{ github.event_name == 'pull_request' }}
      run: |
          REPO="https://github.com/${{ github.repository }}.git"
          FULL_REPO="${{ github.repository }}"
          REPO_NAME="${FULL_REPO##*/}"
          BASE_BRANCH="${{ github.base_ref }}"

          # Clean the repository directory before starting
          docker run --rm --net=host -v $(pwd):/workspace -w /workspace \
          -e "REPO_NAME=${REPO_NAME}" \
          ${docker_image} /bin/bash -c '
            if [ -d ${REPO_NAME} ]; then
              echo "Directory ${REPO_NAME} exists, removing it..."
              rm -rf ${REPO_NAME}
            fi
          '
          git config --global user.name "FastDeployCI"
          git config --global user.email "fastdeploy_ci@example.com"
          git clone ${REPO} ${REPO_NAME} 
          cd FastDeploy
          if [[ "${IS_PR}"" == "true" ]];then
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr/${{ github.event.pull_request.number }}
            git merge pr/${{ github.event.pull_request.number }}
          else
            git checkout ${{ github.sha }}
          fi
          git log -n 3 --oneline

