name: FastDeploy Code Clone
description: "FastDeploy clone and upload"

on:
  workflow_call:
    inputs:
        bos_dir:
          type: string
          required: false
          default: 'FastDeploy'
  pull_request:
    types: [opened, synchronize]
    branches: [develop, release/**]
    # 新 tag 创建时触发（示例匹配以 v 开头的 tag）
  push:
    branches:
      - develop
      - release/**
    tags:
      - 'v*'

jobs:
  code-clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone FastDeploy
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' 
                && github.event.pull_request.head.ref 
                || github.ref_name }}
          submodules: 'recursive'
          fetch-depth: 1000

      - name: Merge PR (if needed)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Fetching and merging PR..."
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr/${{ github.event.pull_request.number }}
          git merge --no-ff pr/${{ github.event.pull_request.number }}
          echo "PR Branch log "
          git log --oneline -n 5 pr/${{ github.event.pull_request.number }} 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Code Info Show and Upload
        env:
          AK: ${{ secrets.BOS_AK }}
          SK: ${{ secrets.BOS_SK }}
        run: |
          git config --unset http.https://github.com/.extraheader
          git submodule foreach --recursive sh -c "git config --local --unset-all 'http.https://github.com/.extraheader'"
          git submodule foreach --recursive sh -c "git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'"
          echo "Current HEAD Log:"
          git log --oneline -n 5
          tree -L 3
          cd ..
          tar -zcf FastDeploy.tar.gz FastDeploy
          if [[ "${{ github.event_name }}" == "pull_request" ]];then
            commit_id=${{ github.event.pull_request.head.sha }}
            pr_num=${{ github.event.pull_request.number }}
            target_path=paddle-qa/PR/FastDeploy/${pr_num}/${commit_id}
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            commit_id=${{ github.sha }}
            tag_name=${{ github.ref_name }}
            target_path=paddle-qa/TAG/FastDeploy/${tag_name}/${commit_id}
          else
            commit_id=${{ github.sha }}
            branch_name=${{ github.ref_name }}
            target_path=paddle-qa/BRANCH/FastDeploy/${branch_name}/${commit_id}
          fi
          wget  -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddlePaddle/PaddleTest/tools/bos_tools.py 
          push_file=$(realpath bos_tools.py)
          python -m pip install bce-python-sdk==0.9.29
          tree -L 3
          python ${push_file} FastDeploy.tar.gz ${target_path}
