on:
  workflow_call:
    inputs:
      workflow-name:
        required: true
        type: string
    secrets:
      github-token:
        required: true
    outputs:
      can-skip:
        description: "Whether the workflow can be skipped."
        value: ${{ jobs.check-bypass.outputs.can-skip }}

jobs:
  check-bypass:
    name: Check bypass
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI_TEAM_MEMBERS: '["yuanlehome","YuanRisheng","Jiang-Jia-Jun","DDDivano","XieYunshen","EmmonsCurse"]'
    outputs:
      can-skip: ${{ steps.final-output.outputs.can-skip }}
    steps:
      - name: Cleanup
        run: |
          rm -rf * .[^.]*

      - id: check-bypass
        name: Check Bypass
        uses: PFCCLab/ci-bypass@v1
        with:
          github-token: ${{ secrets.github-token }}
          non-pull-request-event-strategy: 'never-skipped'
          type: 'composite'
          composite-rule: |
            {
              "any": [
                {
                  "type": "labeled",
                  "label": ["skip-ci: ${{ inputs.workflow-name }}", "skip-ci: all"],
                  "username": ${{ env.CI_TEAM_MEMBERS }}
                },
                {
                  "type": "commented",
                  "comment-pattern": [".*/skip-ci ${{ inputs.workflow-name }}.*", ".*/skip-ci all.*"],
                  "username": ${{ env.CI_TEAM_MEMBERS }}
                }
              ]
            }

      - id: check-only-docs
        name: Check if only Docs files changed
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: |
          files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')

          can_skip=true
          for f in $files; do
            if [[ ! "$f" =~ \.(md|txt|yaml|yml)$ ]]; then
              can_skip=false
              break
            fi
          done

          echo "can_skip=$can_skip" >> $GITHUB_OUTPUT

      - id: final-output
        name: Final can-skip result
        run: |
          if [[ "${{ steps.check-bypass.outputs.can-skip }}" == "true" || "${{ steps.check-only-docs.outputs.can_skip }}" == "true" ]]; then
            echo "can-skip=true" >> $GITHUB_OUTPUT
          else
            echo "can-skip=false" >> $GITHUB_OUTPUT
          fi
