name: CI

on:
  pull_request:
    branches:
      - develop
      - 'release/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print current runner name
        run: |
          echo "The current CI tasks have been migrated to PreCe and will be deprecated soon."
