name: CI_METAX

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  metax-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: MetaX-MACA/simple-jenkins-githubaction@v1.0
        with:
          job_name: paddle_fastdeploy_metax_smoketest
          username: ${{ secrets.METAX_JENKINS_USER }}
          api_token: ${{ secrets.METAX_JENKINS_API_TOKEN }}
          pr_num: ${{ github.event.pull_request.number }}
          project_branch: "develop"
