name: CI_METAX

on:
  pull_request:
    branches:
      - develop
      - 'release/*'
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:

jobs:
  CI_METAX:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        env:
          USER: ${{ secrets.METAX_JENKINS_USER }}
          TOKEN: ${{ secrets.METAX_JENKINS_API_TOKEN }}
        uses: MetaX-MACA/simple-jenkins-githubaction@v1.0
        with:
          job_name: paddle_fastdeploy_metax_smoketest
          username: ${{USER}}
          api_token: ${{TOKEN}}
          pr_num: ${{ github.event.pull_request.number }}
          project_branch: "develop"
