name: Nightly FastDeploy Build

on:
  workflow_dispatch:
  schedule:
    # Trigger at 03:00 AM China Standard Time (CST)
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: [self-hosted, GPU-L20-4Card]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 20  
      - name: Git config and show log
        shell: bash
        run: |
          git config --global user.name "FastDeployCI"
          git config --global user.email "fastdeploy_ci@example.com"
          git checkout ${{ github.sha }}
          git log -n 3 --oneline
      - name: Run FastDeploy Build Plugin
        id: build_step
        uses: ./.github/actions/fastdeploy-build-gpu
        with:
          DOCKER_IMAGE: "ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleqa:cuda126-py310"
          COMPILE_ARCH: "80,90"
          FD_VERSION: "2.0.0"
          WITH_NIGHTLY_BUILD: "ON"
      - name: Show build result
        run: |
          echo "Built wheel path: ${{ steps.build_step.outputs.wheel_path }}"
          ls -ll ${{ steps.build_step.outputs.wheel_path }}

